export const AppActionTypes = {
    TEST_ACTION: '[APP] TEST_ACTION',
    GET_STAFF_DATA: '[APP] GET_STAFF_DATA',
    SET_SELECTED_DAY: '[APP] SET_SELECTED_DAY',
    SET_START_END_TIME: '[APP] SET_START_END_TIME',
    SET_CALENDAR_SHOW_TYPE: '[APP] SET_CALENDAR_SHOW_TYPE',
}